### ISSUE TITLE
Error: No JSON object could be decoded on login from api.py

### ISSUE THREAD

**Issue by pentafive** [tdickman/simple-tv-api#1]
I am trying to test out your api scripts but can't get past the login. I did manually test logging into https://us.simple.tv/Auth/SignIn and got the following returned (ID masked)

```
{"Success":true,"returnUrl":"http://us-my.simple.tv","MediaServerID":"********-****-****-*****-**************"}
```

Here is the error message:

```
titan:/usr/local/simple-tv-api # python download.py 
Enter email: pentafive@gmail.com
Enter password: 
Logging in...
Traceback (most recent call last):
  File "download.py", line 9, in <module>
    simple = api.SimpleTV(username, password)
  File "/usr/local/simple-tv-api/api.py", line 14, in __init__
    self._login(username, password)
  File "/usr/local/simple-tv-api/api.py", line 24, in _login
    resp = json.loads(r.text)
  File "/usr/local/lib/python2.7/json/__init__.py", line 326, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by superm1** [comment]
I've found that the URL needs to be changed to https://us.simple.tv/Auth/SignIn  however that doesn't fix all the problems.

**Comment by tdickman** [comment]
I'm fairly sure that the api changed on their end (simple tv's) somewhat
since I originally developed the program. Unfortunately I haven't had a
chance to update it since then. Feel free to send a pull request if you get
it working - when I get a chance, I'll try to update it.

If you look on the simple tv forums, there is a thread with a few other
programs built based off of this that are more up to date, and might work
better for you.

On Tue, Jun 10, 2014 at 4:52 PM, Mario Limonciello <notifications@github.com

**Comment by tdickman** [comment]
Finally had some time to look into this. @superm1 was right about the base url - this fixed most of the issues. There were a few other small api changes that should be solved by the newest commit.
